### ISSUE TITLE
Integrate mcad with KubeStellar to support AppWrapper deployment in multi-cluster environment

### ISSUE THREAD

**Issue by cwiklik** [project-codeflare/mcad#156]
When a new AppWrapper is created on the HUB and reaches `dispatching` state, the Dispatcher should create a BindingPolicy object for it. This KubeStellar Custom Resource associates AppWrapper with a target Work Execution Cluster (WEC) where the workload will be deployed.
 
To simplify implementation, a user needs to add a label to the AppWrapper  specifying the WEC name. Once the BindingPolicy is created, KubeStellar will down sync the AppWrapper to the target WEC where the Runner will deploy its workload. While the workload progresses, KubeStellar will propagate status up to the HUB to update the AW. 

On AppWrapper deletion, the Dispatcher will delete its BindingPolicy which will cascade to the WEC and delete the AW.

**Comment by dgrove-oss** [comment]
Done in #157
