### ISSUE TITLE
feat: Allow 0 restarts

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [project-codeflare/mcad#168]
This is a feature request.

Currently `maxNumRequeuings: 0` means infinite restarts. Allow no restarts when the pod has completed or crashed with some error.
Avoid restarts will allow looking at the error logs when the pod crashes.

https://github.com/project-codeflare/mcad/blob/1761856c9bd0c0f5ac025cb7def9bf77eb0f49d8/api/v1beta1/appwrapper_types.go#L83-L85

https://github.com/project-codeflare/mcad/blob/1761856c9bd0c0f5ac025cb7def9bf77eb0f49d8/internal/controller/runner.go#L211-L215

**Comment by dgrove-oss** [comment]
MCAD and the appwrapper v1/beta CRD is being replaced by [AppWrapper](https://github.com/project-codeflare/appwrapper) and the v1/beta2 version of the CRD defined there.  

The requested feature is supported in the new codebase by setting `retryCount` to 0 and `DeletionOnFailureGracePeriod` to a non-zero duration.   For details, see https://project-codeflare.github.io/appwrapper/arch-fault-tolerance/.

**Comment by HarikrishnanBalagopal** [comment]
> MCAD and the appwrapper v1/beta CRD is being replaced by [AppWrapper](https://github.com/project-codeflare/appwrapper) and the v1/beta2 version of the CRD defined there.
> 
> The requested feature is supported in the new codebase by setting `retryCount` to 0 and `DeletionOnFailureGracePeriod` to a non-zero duration. For details, see https://project-codeflare.github.io/appwrapper/arch-fault-tolerance/.

Awesome, is there a timeline for a stable release soon?
