### ISSUE TITLE
[UX] missing reason for pending

### ISSUE THREAD

**Issue by asm582** [project-codeflare/mcad#34]
When AW is fired on the cluster that has no GPUs the AW remains pending but the reason for pending is unknown : 

```
Status:
  Restarts:  0
  State:     Pending
  Transitions:
    State:  Pending
    Time:   2023-10-10T18:35:22Z
```

we should add `Insufficient resources to dispatch appwrapper` as the reason

**Comment by tardieu** [comment]
Until we have alternative reasons for not to dispatch an AppWrapper I suggest we sit on this one. For now, this is a tautology.

**Comment by dgrove-oss** [comment]
Done in #100.
