### ISSUE TITLE
[core] reuse conditions from MCADv1

### ISSUE THREAD

**Issue by asm582** [project-codeflare/mcad#4]
We need to use the same conditions names and types as present in MCADv1 https://github.com/project-codeflare/multi-cluster-app-dispatcher/blob/6fb5e32f6097f3b0ed1d1f4164dd137601939062/pkg/apis/controller/v1beta1/appwrapper.go#L241 to make testing easier

**Comment by tardieu** [comment]
I am inclined to close this as won't fix. Very few tests rely on conditions, which we can simply rewrite.

**Comment by dgrove-oss** [comment]
Closing this particular issue as won't fix.   
I ported the tests that do look at the Status with minor effort to mcad v2's similar concepts.
